TeamViewer User Settings
# It is not recommended to edit this file manually


[int32] BetterChatSplitterPos = 250
[int32] BetterChatWindowRect = 5538 612 697 527
[bin  ] BetterChat_Key_For_FileOutboxStorage = 080000081000100087aa8e22c6efff917892b3a243fee1a6443a73eee0b5f759601919a9f516c38f37a683c785897de78d5ca451a70594379449826b855d8da141754afa1977b194f996c081261585e0aaaa74099a9e51a1
[strng] BuddyLoginName = "tom@rocksalt.computer"
[int32] ClientScaling_Mode = 0
[int32] ColorScheme = 2
[int32] ConfigurationRMAssetReportingEnabled = 1
[int32] ConfigurationSessionSummaryEnabled = 1
[int32] Enable1EClient = 1
[strng] FT_Start_Directories = "1625977382?/home/tom/Documents/temp|" "1112848873?/home/tom/Downloads|C:/Users/Jeanne Ordaz/Desktop" "769741183?/home/tom/Downloads|C:/Users/Charlotte/Desktop" "362120072?/home/tom/Downloads|/Users/carolinewhite/Desktop" "254882616?/home/tom/Downloads|C:/Users/Isabella/OneDrive - Supportive Care (UK) Limited/Desktop" "1249420832?/home/tom/Downloads|C:/Users/Justin Ziegler/OneDrive - Marchini Curran Associates Ltd/Desktop" "1109937663?/home/tom/Downloads|C:/Users/Antony Phillips/Desktop" "163088584?/home/tom/Downloads|C:/Users/Rocksalt/Desktop" "993816911?/home/tom/Desktop|\\its-file01/Redirected Folders$/pablo.power/Downloads" "496070932?/home/tom/Desktop|\\its-file01/Redirected Folders$/pablo.power/Desktop" "1275106434?/home/tom/Downloads|C:/Users/Chris Taylor/Desktop" "129285926?/home/tom/Downloads|C:/Users/Joshua von Fragstein/OpenVPN/config" "391485354?/home/tom/Downloads|C:/Users/Rocksalt/Desktop" "425586297?/home/tom/Downloads|C:/Users/NicholasLyddon/Desktop" "1692682753?/home/tom/Downloads|C:/Users/Sarah/Downloads" "1407641183?/home/tom/Downloads|C:/Rocksalt" "1418710477?/home/tom/Downloads|C:/Rocksalt" "1887168986?/home/tom/Downloads|C:/Rocksalt" "679060157?/home/tom/Downloads/ntdll|C:/Rocksalt" "461901374?/home/tom/Downloads|C:/Users/Rocksalt/Desktop" "1310512681?/home/tom/Documents|C:/Users/Gemma/Downloads" "805284186?/home/tom/Downloads|C:/Rocksalt" "1217862710?/home/tom/Downloads|C:/Users/zeeshan/Downloads" "1425389160?/home/tom/Downloads|C:/Rocksalt" "1470257056?/home/tom/Dev/Windows|C:/Rocksalt" "1479119518?/home/tom/Downloads|C:/Rocksalt" "998769356?/home/tom/Documents|C:/Rocksalt" "1594917877?/home/tom/Downloads|C:/rocksalt" "1777044163?/home/tom/Dev/Windows|E:" "641575684?/home/tom/Downloads|/Users/ayeeshamx/Downloads" "1452917882?/home/tom/Downloads|C:/Rocksalt" "993300731?/home/tom/Dev/Windows|C:" "901553770?/home/tom/Downloads|C:/Rocksalt" "1980219240?/home/tom/Downloads|C:/Rocksalt" "1079647467?/home/tom/Downloads|C:/Rocksalt"
[int32] LastCorrectorRun = 2
[int32] Last_Active_License = 1
[int32] MainWindowSize = 989 541 412 514
[strng] MultiMedia\AudioUserSelectedCapturingEndpoint = "null"
[strng] MultiMedia\AudioUserSelectedRenderingEndpoint = "null"
[int32] MultiMedia\RemoteAudioReceiveEnabled = 0
[int32] OnboardingTaskState = 1 1 1
[int32] PilotTabWasEnabled = 1
[int32] Remote_RemoteCursor = 1
[bin  ] SUID = 007d911002ee41c5b135b761559cdfaf
[int32] SendWindowsKeys = 1
[int32] SuitedForOnboarding = 1
[strng] Username = "tom-bull"
